name: book_breeze
description: "BookBreeze is a simple online platform that serves as a virtual haven for book enthusiasts. Seamlessly curating an extensive collection of literary treasures from various web sources, BookBreeze offers a unique reading experience. By aggregating and organizing books, articles, and stories available across the internet, users can discover, access, and explore a vast array of literary content all in one place. With an intuitive interface, personalized recommendations, and easy navigation, BookBreeze provides a convenient and enjoyable reading journey for users to immerse themselves in captivating stories and enriching content sourced from diverse online sources. Whether seeking classic novels, contemporary articles, or niche genres, BookBreeze is the go-to destination for discovering and rediscovering the joy of reading."

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flex_color_scheme: ^7.3.1
  flutter_native_splash: ^2.3.5
  dio: ^5.3.3
  google_nav_bar: ^5.0.6
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  # - lib/asset/icons
  # - lib/asset/svg_image

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
